services:

    moovone_movie.rss_handler:
        class: AppBundle\View\WithTotalViewHandler
        arguments: ['@jms_serializer']

    moovone_movie.view_handler:
        parent: 'fos_rest.view_handler.default'
        calls:
            - ['registerHandler', [ 'moovone_format', [ '@moovone_movie.rss_handler', 'createResponse'] ] ]