services:

    moovone_movie.json_view_handler:
        class: AppBundle\View\WithTotalViewHandler
        arguments: ['@jms_serializer']

    moovone_movie.view_handler:
        parent: 'fos_rest.view_handler.default'
        calls:
            - ['registerHandler', [ 'moovone_format', [ '@moovone_movie.json_view_handler', 'createResponse'] ] ]

    moovone_movie.movies_manager:
        class: AppBundle\Domain\MoviesManager
        arguments: ['@doctrine', '@validator']